public class BatchMonitorConstants {

    //EXCEPTION TYPES
    public static final string  ASSERT_EXCEPTION =  'AssertException';
    public static final string  AURA_EXCEPTION =  'AuraException';
    public static final string  AURAHANDLED_EXCEPTION =  'AuraHandledException';
    public static final string  ASYNC_EXCEPTION =  'AsyncException';
    public static final string  BIGOBJECT_EXCEPTION =  'BigObjectException';
    public static final string  CALLOUT_EXCEPTION =  'CalloutException';
    public static final string  DML_EXCEPTION =  'DmlException';
    public static final string  EMAIL_EXCEPTION =  'EmailException';
    public static final string  EXTERNALOBJECT_EXCEPTION =  'ExternalObjectException';
    public static final string  FINAL_EXCEPTION =  'FinalException';
    public static final string  FLOW_EXCEPTION =  'FlowException';
    public static final string  HANDLED_EXCEPTION =  'HandledException';
    public static final string  ILLEGALARGUMENT_EXCEPTION =  'IllegalArgumentException';
    public static final string  INVALIDPARAMETERVALUE_EXCEPTION =  'InvalidParameterValueException';
    public static final string  LIMIT_EXCEPTION =  'LimitException';
    public static final string  JSON_EXCEPTION =  'JSONException';
    public static final string  LIST_EXCEPTION =  'ListException';
    public static final string  MATH_EXCEPTION =  'MathException';
    public static final string  NOACCESS_EXCEPTION =  'NoAccessException';
    public static final string  NODATAFOUND_EXCEPTION =  'NoDataFoundException';
    public static final string  NOSUCHELEMENT_EXCEPTION =  'NoSuchElementException';
    public static final string  NULLPOINTER_EXCEPTION =  'NullPointerException';
    public static final string  QUERY_EXCEPTION =  'QueryException';
    public static final string  REQUIRED_FEATURE_MISSING_EXCEPTION =  'RequiredFeatureMissing';
    public static final string  SEARCH_EXCEPTION =  'SearchException';
    public static final string  SECURITY_EXCEPTION =  'SecurityException';
    public static final string  SERIALIZATION_EXCEPTION =  'SerializationException';
    public static final string  SOBJECT_EXCEPTION =  'SObjectException';
    public static final string  STRING_EXCEPTION =  'StringException';
    public static final string  TYPE_EXCEPTION =  'TypeException';
    public static final string  UNEXPECTED_EXCEPTION =  'UnexpectedException';
    public static final string  VISUALFORCE_EXCEPTION =  'VisualforceException';
    public static final string  XML_EXCEPTION = 'XmlException';
    
}
